[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sciSOM"
version = "0.0.0"
decription = "SOM software for scientists"
dependencies = [
    'viffIO>=0.0.1',
    'numpy>=1.22.4',
    'strax>=1.5.2',
    'matplotlib>=3.7.1'
]